title: Max Willsey
email: me@mwillsey.com
description: >- # this means to ignore newlines until "baseurl:"
  Max Willsey's personal site.
baseurl: ""
url: "https://mwillsey.com"

permalink: /:categories/:title

markdown: kramdown
kramdown:
  math_engine: nil

future: true

exclude:
  - .vscode/
  - .github/
